In [5]:
print("Hello world")

Hello world


In [6]:
print("Schrodinger Equation")

Schrodinger Equation


In [ ]:
import numpy as np 



def matrix_1(n):
    H=np.zeros((n,n))


    for i in range(n):
        H[i,i]= -2

    for j in range(n-1):
        H[j,j+1]= 1
        H[j+1,j]=1

    print(H)

matrix_1(500)









[[-2.  1.  0. ...  0.  0.  0.]
 [ 1. -2.  1. ...  0.  0.  0.]
 [ 0.  1. -2. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -2.  1.  0.]
 [ 0.  0.  0. ...  1. -2.  1.]
 [ 0.  0.  0. ...  0.  1. -2.]]
